package org.helmo.gbeditor.infrastructures.jdbc;

public class SqlQueries {

    /**
     * Create tables
     */
    public static final String CREATE_BOOK_TABLE_STMT = "CREATE TABLE BOOK(" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "title VARCHAR(150) NOT NULL, " +
            "summary VARCHAR (500) NOT NULL," +
            "author VARCHAR(100) NOT NULL," +
            "isbn VARCHAR(13))";

    public static final String CREATE_PAGE_TABLE_STMT = "CREATE TABLE PAGE(" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  " +
            "text VARCHAR(3000) NOT NULL," +
            "num INT," +
            "book_id INT," +
            "FOREIGN KEY(book_id) REFERENCES BOOK(id))";

    public static final String CREATE_CHOICE_TABLE_STMT = "CREATE TABLE CHOICE(" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "text VARCHAR(150) NOT NULL," +
            "page_id INT," +
            "FOREIGN KEY(page_id) REFERENCES PAGE(id))";


    /**
     * Inserts
     */
    public static final String INSERT_BOOK_STMT = "INSERT INTO BOOK" +
            "(title, summary, author, isbn)" +
            " VALUES (?, ?, ?, ?)";

    public static final String INSERT_PAGE_STMT = "INSERT INTO PAGE" +
            "(text, num, book_id)" +
            " VALUES (?, ?, ?)";

    public static final String INSERT_CHOICES_STMT = "INSERT INTO CHOICE" +
            "(text, page_id)" +
            " VALUES (?, ?)";

    /**
     * Selects
     */
    public static final String SELECT_BOOKS_BY_AUTHOR_STMT = "SELECT * FROM BOOK" +
            "WHERE isbn LIKE '%?%'";

    public static final String SELECT_PAGES_BY_BOOK_STMT = "SELECT * FROM PAGE" +
            "WHERE book_id = ?";

    public static final String SELECT_CHOICES_BY_BOOK_STMT = "SELECT * FROM CHOICES C" +
            "JOIN PAGE P ON P.id = C.page_id" +
            "WHERE book_id = ?";

}
